import favouriteActiveIcon   from './icons/favouriteActiveIcon.png';
import favouriteInactiveIcon from './icons/favouriteInactiveIcon.png';
import searchIcon from './icons/searchIcon.png';
import rightArrowIcon from './icons/rightArrowIcon.png';
import downArrowIcon from './icons/downArrowIcon.png';
import filterIcon from './icons/filterIcon.png';
import leftArrowIcon from './icons/leftArrowIcon.png';
import clickedIcon from './icons/clickedIcon.png';
import closeIcon from './icons/closeIcon.png';
import removeIcon from './icons/subIcon.png';
import addIcon from './icons/addIcon.png';
import threeDotIcon from './icons/threeDot.png';
import amexIcon from './icons/amex.png';
import applePayIcon from './icons/applepay.png';
import gPayIcon from './icons/gpay.png';
import mastercardIcon from './icons/mastercard.png';
import paypalIcon from './icons/paypal.png';
import visaIcon from './icons/visa.png';
import cartIcon from './icons/CartIcon.png';

export { favouriteActiveIcon, favouriteInactiveIcon, searchIcon, rightArrowIcon, downArrowIcon, filterIcon, leftArrowIcon, clickedIcon, closeIcon, removeIcon, addIcon, threeDotIcon, amexIcon, applePayIcon, gPayIcon, mastercardIcon, paypalIcon, visaIcon, cartIcon };